DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    first_name  VARCHAR(250) NOT NULL,
    last_name   VARCHAR(250) NOT NULL,
    description VARCHAR(250) DEFAULT NULL
);