DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    firstName  VARCHAR(250) NOT NULL,
    lastName   VARCHAR(250) NOT NULL,
    description VARCHAR(250) DEFAULT NULL
);